Transform: AWS::Serverless-2016-10-31

Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: HelloWorld
      CodeUri: src/HelloWorld/bin/Release/net10.0/HelloWorld.zip
      Runtime: dotnet10
      Architectures: [x86_64]
      MemorySize: 1769
      Timeout: 20
      AutoPublishAlias: live
      Events:
        Api:
          Type: HttpApi
          Properties:
            TimeoutInMillis: 20000

Outputs:
  ApiUrl:
    Value: !Sub https://${ServerlessHttpApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}
  Function:
    Value: !Ref Function
